<a href="https://colab.research.google.com/github/ummadiviany/ML_Workshop_APSSDC/blob/master/ML_Workshop_APSSDC_Day2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Tuples in Python**

### 1)Convert List to Tuples

In [1]:
values=list(map(int, input("Enter multiple values:").split(',')))
print("Output as a List  : ",values)
print("Output as a Tuples:",tuple(values)) # tuple() function directly converts the list to tuple

Enter multiple values:1,2,3,4
Output as a List  :  [1, 2, 3, 4]
Output as a Tuples: (1, 2, 3, 4)


### 2)Use List comprehension to create a List.

*   Input : Sequence of numbers seperated by comma
*   Output: Squares of odd numbers



In [2]:
values=list(map(int, input("Enter multiple values:").split(',')))
oddsq=[x*x for x in values if (x%2 !=0) ] #Use list compresion to create a new list
print("Square of Odd numbers:",oddsq)

Enter multiple values:1,2,3,4,5,6,7,8
Square of Odd numbers: [1, 9, 25, 49]


### 3)Write a program to take the Integer as a Input and to make an Operation(take input as 'a') to perform a+aa+aaa+aaaa.

In [7]:
val=input("Enter a Number:")
numlist=[int(val*i) for i in range(1,5)]
print("The created list is:",numlist)
print("The sum of list is:",sum(numlist))

Enter a Number:5
The created list is: [5, 55, 555, 5555]
The sum of list is: 6170


### 4)Create a Odd numbered tuple using tuple comprehensions.


*   Input  : (1,10) =1,2,3,4,5,6,7,8,9,10
*   Output : (1,3,5,7,9)



In [11]:
(val1),(val2) = input("Enter Min Range and Max Range : ").split(',')
val1=int(val1)
val2=int(val2)
tup1=tuple(x for x in range(val1,val2+1) if (x%2 != 0))
print("The odd numbered tuple is: ",tup1)


Enter Min Range and Max Range : 1,10
The odd numbered tuple is:  (1, 3, 5, 7, 9)


### 5) Wite a program to sort the (name,age,score) tuples by ascending order. Where name is string,age and score are integers.The tuples are input by console.The sort priority criteria is name>age>score
*   Input  : Tom,19,80
              John,20,90
              Jony,17,91
              Jony,17,93
              Json,21,85
*   Output : 

In [15]:
n=int(input("Enter number of rows:"))
lst= [input("Enter each row:").split(",") for i in range(0, n)]
print("The given data is : ",lst)
lst.sort(key= lambda x:(x[0],x[1],x[2]))
print("The sorted data is: ",lst)

Enter number of rows:3
Enter each row:Tom,19,80
Enter each row:John,20,90
Enter each row:Jony,17,91
The given data is :  [['Tom', '19', '80'], ['John', '20', '90'], ['Jony', '17', '91']]
The sorted data is:  [['John', '20', '90'], ['Jony', '17', '91'], ['Tom', '19', '80']]


# **Dictionaries in Python**

### 6)Creating a dict with integer and mixed keys

With Integer Keys

In [16]:
Dict={1:'cpu',2:'monitor',3:'mouse'}
print("The created dictionary is :",Dict)

The created dictionary is : {1: 'cpu', 2: 'monitor', 3: 'mouse'}


With Mixed Keys

In [17]:
Dict={'component1':'cpu','component2':'monitor','component3':'mouse'}
print("The created dictionary is :",Dict)

The created dictionary is : {'component1': 'cpu', 'component2': 'monitor', 'component3': 'mouse'}


Creating a dictionary with **dict()** method

In [18]:
Dict=dict({1:'cpu',2:'monitor',3:'mouse'})
print("The created dictionary is :",Dict)

The created dictionary is : {1: 'cpu', 2: 'monitor', 3: 'mouse'}


Creating a dictionary with **Each item as pair**

In [23]:
Dict=dict([(1,'cpu'),(2,'monitor'),(3,'mouse')])
print("The created dictionary is :",Dict)

The created dictionary is : {1: 'cpu', 2: 'monitor', 3: 'mouse'}


### 7)Acessing elements in Dictionary

In [26]:
print("The element with key 1 in Dict is:",Dict[1])
print("The element with key 2 in Dict is:",Dict[2])
print("The element with key 3 in Dict is:",Dict[3])

The element with key 1 in Dict is: cpu
The element with key 2 in Dict is: monitor
The element with key 3 in Dict is: mouse


In [30]:
print ("The element with key 1 in Dict are : ") 
for i in Dict: 
    print(i, Dict[i])

The element with key 1 in Dict are : 
1 cpu
2 monitor
3 mouse


### 8)Creating a nested dictionary

In [31]:
DictNest={1:'monitor',2:'keyboard',3:'mouse',4:{'os1':'ubuntu','os2':'windows'}}
print("The created nested dictionary is :",DictNest)

The created nested dictionary is : {1: 'monitor', 2: 'keyboard', 3: 'mouse', 4: {'os1': 'ubuntu', 'os2': 'windows'}}


In [39]:
DictNest=dict([(1,'monitor'),(2,'keyboard'),(3,'mouse'),(4,dict([('os1','ubuntu'),('os2','windows')]))])
print("The created nested dictionary is :",DictNest)

The created nested dictionary is : {1: 'monitor', 2: 'keyboard', 3: 'mouse', 4: {'os1': 'ubuntu', 'os2': 'windows'}}


### 9)Updating Dictionaries

In [50]:
Dict={}
print("Empty dictionary",Dict)


Empty dictionary {}


In [51]:
Dict[0]='python'
Dict[1]='c'
Dict[2]='tf'
print("Dictionary with added elements",Dict)

Dictionary with added elements {0: 'python', 1: 'c', 2: 'tf'}


In [52]:
Dict[4]=1,2,3
print("Dictionary after adding 3  elements",Dict)


Dictionary after adding 3  elements {0: 'python', 1: 'c', 2: 'tf', 4: (1, 2, 3)}


In [53]:
Dict[0]='cython'
print("Dictionary with updating 0th element,replacing python with cython",Dict)

Dictionary with updating 0th element,replacing python with cython {0: 'cython', 1: 'c', 2: 'tf', 4: (1, 2, 3)}


In [54]:
Dict[0]={'languages':{1:'python',2:'cython'}}
print("Dictionary after updating 0th element with nested dict",Dict)


Dictionary after updating 0th element with nested dict {0: {'languages': {1: 'python', 2: 'cython'}}, 1: 'c', 2: 'tf', 4: (1, 2, 3)}


In [55]:
del Dict[4]
print("Dictionary after deleting 4th element",Dict)

Dictionary after deleting 4th element {0: {'languages': {1: 'python', 2: 'cython'}}, 1: 'c', 2: 'tf'}


In [58]:
del Dict[0]['languages'][2]
print("Dictionary after deleting 0th and 2nd element",Dict)

Dictionary after deleting 0th and 2nd element {0: {'languages': {1: 'python'}}, 1: 'c', 2: 'tf'}


In [59]:
Dict.pop(1)
print("Dictionary after popping element with key 1",Dict)

Dictionary after popping element with key 1 {0: {'languages': {1: 'python'}}, 2: 'tf'}


In [60]:
popped=Dict.popitem()
print("The popped element is :",popped)
print("Dictionary after popping an arbitary element :",Dict)

The popped element is : (2, 'tf')
Dictionary after popping an arbitary element : {0: {'languages': {1: 'python'}}}


### Dictionary Methods
Methods 	Description


---


copy() 	They copy() method returns a shallow copy of the dictionary.


---


clear() 	The clear() method removes all items from the dictionary.


---


pop() 	Removes and returns an element from a dictionary having the given key.


---


popitem() 	Removes the arbitrary key-value pair from the dictionary and 
returns it as tuple.

---


get() 	It is a conventional method to access a value for a key.


---


dictionary_name.values() 	returns a list of all the values available in a given dictionary.


---


str() 	Produces a printable string representation of a dictionary.


---


update() 	Adds dictionary dict2’s key-values pairs to dict


---

setdefault() 	Set dict[key]=default if key is not already in dict


---

keys() 	Returns list of dictionary dict’s keys


---

items() 	Returns a list of dict’s (key, value) tuple pairs


---

has_key() 	Returns true if key in dictionary dict, false otherwise


---

fromkeys() 	Create a new dictionary with keys from seq and values set to value.


---

type() 	Returns the type of the passed variable.


---

cmp() 	Compares elements of both dict.


---



### **Assignment**
Write a program to take inputs as withdraw and deposit and give the current balance as output.

Input: D 200
       D 200
       W 200
       D 100

Output: Balance - 500

In [68]:
n=int(input("Enter number of transactions:"))
lst= [input("Enter transaction type and amount:").split() for i in range(0, n)]
Acc={'balance':0}
TransHist=[]
for trans in lst:
  if(trans[0]=='D'):
    Acc['balance']+=int(trans[1])
    TransHist.append("")
  elif(trans[0]=='W'):
    Acc['balance']-=int(trans[1])
print("The Main Account balance is:",Acc['balance'])
print("The tranaction log:",lst)

Enter number of transactions:3
Enter transaction type and amount:D 100
Enter transaction type and amount:D 1000
Enter transaction type and amount:W 500
The Main Account balance is: 600


# Afternoon Session

point wise multiplication of two arrays in vannila python

In [71]:
l2=l1=[1,2,3]
print("Adding two lists:"l1+l2) # Actually its not the correct way so we are going with numpy

[1, 2, 3, 1, 2, 3]


# Numpy-Python

In [74]:
import numpy as np
l2=l1=[1,2,3]
l1=np.array(l1)
l2=np.array(l2)
print("Adding two arrays:",l1+l2)
print("Multiplying two arrays:",l1*l2)
print("Subracting two arrays:",l1-l2)
print("Dividing two arrays:",l1/l2)

Adding two arrays: [2 4 6]
Multiplying two arrays: [1 4 9]
Subracting two arrays: [0 0 0]
Dividing two arrays: [1. 1. 1.]


In [75]:
arr=np.arange(10,1,-2)
print(arr)

[10  8  6  4  2]


In [81]:
newarr=arr[np.array([0,1,2,3])]
print(newarr)

[10  8  6  4]


In [82]:
newarr=arr[np.array([0,1,-3])]
print(newarr)

[10  8  6]
